apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: runseb/kubewatch:v0.0.1
    args:
      - --handler=slack
    env:
      - name: KW_SLACK_TOKEN
        valueFrom:
          secretKeyRef:
            name: kubewatch
            key: token
      - name: KW_SLACK_CHANNEL
        valueFrom:
            secretKeyRef:
              name: kubewatch
              key: channel
    imagePullPolicy: Always
    name: kubewatch
  - image: gcr.io/skippbox/kubectl:v1.3.0
    args:
      - proxy
      - "-p"
      - "8080"
    name: proxy
    imagePullPolicy: Always
  restartPolicy: Always
